#!/bin/bash
negro="\e[1;30m" && azul="\e[1;34m" && verde="\e[1;32m" && cian="\e[1;36m" && rojo="\e[1;31m" && purpura="\e[1;35m" && amarillo="\e[1;33m" && blanco="\e[1;37m" && black="$(tput setaf 0)" && red="$(tput setaf 1)" && green="$(tput setaf 2)" && yellow="$(tput setaf 3)" && blue="$(tput setaf 4)" && magenta="$(tput setaf 5)" && cyan="$(tput setaf 6)" && white="$(tput setaf 7)" && rst="$(tput sgr0)"
color() {
    BLANCO='\033[1;37m' && ROJO='\e[1;31m' && VERDE='\e[32m' && AMARELO='\e[33m'
    AZUL='\e[34m' && MAGENTA='\e[35m' && MAG='\033[1;36m' && NEGRITA='\e[1m' && SINCOLOR='\e[0m'
    case $1 in
    -ne) cor="${ROJO}${NEGRITA}" && echo -ne "${cor}${2}${SINCOLOR}" ;;
    -ama) cor="${AMARELO}${NEGRITA}" && echo -e "${cor}${2}${SINCOLOR}" ;;
    -verm) cor="${AMARELO}${NEGRITA}[!] ${ROJO}" && echo -e "${cor}${2}${SINCOLOR}" ;;
    -azu) cor="${MAG}${NEGRITA}" && echo -e "${cor}${2}${SINCOLOR}" ;;
    -verd) cor="${VERDE}${NEGRITA}" && echo -e "${cor}${2}${SINCOLOR}" ;;
    -bra) cor="${ROJO}" && echo -ne "${cor}${2}${SINCOLOR}" ;;
    "-bar2" | "-bar") cor="${ROJO}════════════════════════════════════════════════════" && echo -e "${SINCOLOR}${cor}${SINCOLOR}" ;;
    esac
}
# ------- |	INSTALADOR GENERAL    |   [ufal]   |   VARIABLE:${TXT}
ufal() {
 comando="$1"
  _=$(
    $comando >/dev/null 2>&1
  ) &
  >/dev/null
  pid=$!
  while [[ -d /proc/$pid ]]; do
    echo -ne "  \033[1;33m|"
    for ((i = 0; i < 40; i++)); do
      echo -ne "\033[1;31m▓"
      sleep 0.1
    done
    echo -ne "\033[1;33m|"
    sleep 1s
    echo
    tput cuu1 && tput dl1
  done
  echo -ne "  \033[1;33m|\033[1;31m▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓\033[1;33m| 『  ${verde}${TXT} 』\033[0m\n"
  sleep 1s
}
# ------- |		INSTALADOR DE PAQUETES	[ ufal_dep ]
ufal_dep() {
    comando="$1"
    _=$(
        $comando >/dev/null 2>&1
    ) &
    >/dev/null
    pid=$!
    while [[ -d /proc/$pid ]]; do
        echo -ne "  \033[1;33m|"
        for ((i = 0; i < 20; i++)); do
            echo -ne "\033[1;31m▓"
            sleep 0.08
        done
        echo -ne "\033[1;33m|"
        sleep 0.5s
        echo
        tput cuu1 && tput dl1
    done
    [[ $(dpkg --get-selections | grep -w "$paquete" | head -1) ]] || ESTATUS=$(echo -e "\033[91m  [✗] RECURSO SIN INSTALAR [✗]") &>/dev/null
    [[ $(dpkg --get-selections | grep -w "$paquete" | head -1) ]] && ESTATUS=$(echo -e "\033[1;33m       \033[92m[✓] RECURSO INSTALADO [✓]") &>/dev/null
    echo -ne "  \033[1;33m|\033[1;31m▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓\033[1;33m| $ESTATUS \033[0m\n"
    sleep 0.5s
}
# ------- |	CENTRALIZAR TEXTO 	|[txto]| 	VARIABLE: ${COLOR}
txto() {
    if [[ -z $2 ]]; then
        text="$1"
    else
        col="$1"
        text="$2"
    fi

    while read line; do
        unset space
        x=$(((54 - ${#line}) / 2))
        for ((i = 0; i < $x; i++)); do
            space+=' '
        done
        space+="$line"
        if [[ -z $2 ]]; then
            echo -e "${COLOR}$space"
        else
            msgi "$col" "$space"
        fi
    done <<<$(echo -e "$text")
}
own="\033[0m\033[1;32m＠\033[1;34mｄ\033[1;35mｒ\033[1;31mｏ\033[1;36mｗ\033[1;35mｋ\033[1;34mｉ\033[1;31mｄ\033[1;36m０\033[1;32m１\033[0m"
#ent(){ echo -e "${negro}" && read -p "  ╰► Seleccione su opción: " x ; }
#ejemplo(){
#ent
#}

